version: '3.9'

services:
  backend:
    volumes:
      - ./smart_lounge:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DEBUG: "true"
      RUN_MIGRATIONS: "true"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    command: npm run dev -- --host 0.0.0.0

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  nginx:
    ports:
      - "80:80"
