# Generated by Django 5.1.15 on 2026-09-13 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_seed_default_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name': 'بروفايل الصلاحيات (Profile)', 'verbose_name_plural': 'بروفايلات الصلاحيات'},
        ),
        migrations.AlterModelOptions(
            name='userprofileassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'إسناد بروفايل لمستخدم', 'verbose_name_plural': 'إسنادات البروفايلات'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود البروفايل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='بروفايل نظام أساسي (محمي)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_concurrent_sessions',
            field=models.PositiveIntegerField(default=1, verbose_name='الجلسات المتزامنة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_devices',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للأجهزة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم البروفايل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.JSONField(default=list, verbose_name='الصلاحيات الافتراضية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_delegations', to=settings.AUTH_USER_MODEL, verbose_name='المُسنِد'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط حالياً'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='profiles.profile', verbose_name='البروفايل المسند'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='userprofileassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
