# Generated by Django 5.1.15 on 2026-09-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'موقع / فرع', 'verbose_name_plural': 'المواقع والفروع'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'مستأجر / جهة', 'verbose_name_plural': 'المستأجرين'},
        ),
    ]
