# Generated by Django 5.1.15 on 2026-09-13 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_site_options_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الراوتر التوضيحي (مثال: Lounge Core Gateway)')),
                ('host', models.CharField(max_length=128, verbose_name='عنوان IP أو المضيف (Host)')),
                ('port', models.PositiveIntegerField(default=8728, verbose_name='منفذ RouterOS API (8728 عادي / 8729 مشفر SSL)')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='استخدام اتصال مشفر (API-SSL)')),
                ('username', models.CharField(default='smart_lounge_api', max_length=64, verbose_name='اسم مستخدم API (بأقل الصلاحيات Least Privilege)')),
                ('password_encrypted', models.CharField(max_length=255, verbose_name='مرجع كلمة المرور المشفرة (Decision 57)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_online', models.BooleanField(default=True, verbose_name='متصل بالشبكة (Online)')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال ناجح')),
                ('latency_ms', models.FloatField(default=1.2, verbose_name='زمن الاستجابة (Latency ms)')),
                ('identity', models.CharField(default='MikroTik-Lounge-Core', max_length=64, verbose_name='هوية الراوتر (System Identity)')),
                ('routeros_version', models.CharField(default='RouterOS v7.14', max_length=32, verbose_name='إصدار RouterOS')),
                ('model', models.CharField(default='RB4011iGS+5HacQ2HnD', max_length=64, verbose_name='موديل الجهاز')),
                ('cpu_load', models.PositiveIntegerField(default=8, verbose_name='نسبة استهلاك المعالج %')),
                ('memory_free_mb', models.PositiveIntegerField(default=768, verbose_name='الذاكرة الحرة (MB)')),
                ('uptime', models.CharField(default='18d 14:32:10', max_length=64, verbose_name='مدة العمل (Uptime)')),
                ('active_hotspot_users_count', models.PositiveIntegerField(default=24, verbose_name='عدد مستخدمي الهوتسبوت المتصلين حالياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_routers', to='tenancy.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'موجه MikroTik (MikroTik Router)',
                'verbose_name_plural': 'موجهات MikroTik',
                'ordering': ['name'],
            },
        ),
    ]
