import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الخادم')),
                ('server_type', models.CharField(choices=[('jellyfin', 'Jellyfin Media Server'), ('emby', 'Emby Media Server'), ('plex', 'Plex (Future Ready)'), ('custom', 'Custom HTTP API Server')], default='jellyfin', max_length=30, verbose_name='نوع خادم الوسائط')),
                ('local_url', models.CharField(help_text='مثال: http://192.168.1.50:8096', max_length=255, verbose_name='عنوان السيرفر المحلي (LAN URL)')),
                ('api_key', models.CharField(max_length=255, verbose_name='مفتاح الـ API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('status', models.CharField(choices=[('online', 'متصل (Online)'), ('offline', 'غير متصل (Offline)'), ('error', 'خطأ في الاتصال (Error)'), ('syncing', 'جاري المزامنة (Syncing)')], default='offline', max_length=20, verbose_name='حالة الاتصال')),
                ('last_ping_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال ناجح')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة للمحتوى')),
                ('server_info', models.JSONField(blank=True, default=dict, verbose_name='معلومات الخادم (الإصدار، الهوية)')),
                ('provisioning_enabled', models.BooleanField(default=True, verbose_name='تفعيل إنشاء وإدارة الحسابات')),
                ('provisioning_mode', models.CharField(choices=[('MANUAL', 'يدوي فقط (Manual Only)'), ('AUTO', 'تلقائي (Auto Provisioning)'), ('DISABLED', 'معطل (Disabled)')], default='AUTO', max_length=20, verbose_name='نمط التزويد الافتراضي')),
                ('auto_create_on_first_login', models.BooleanField(default=True, verbose_name='إنشاء تلقائي فور أول تسجيل دخول')),
                ('auto_create_on_playback', models.BooleanField(default=False, verbose_name='إنشاء عند طلب التشغيل')),
                ('auto_disable_on_subscription_expire', models.BooleanField(default=True, verbose_name='تعطيل الحساب تلقائياً عند انتهاء الاشتراك')),
                ('auto_delete_on_user_delete', models.BooleanField(default=False, verbose_name='حذف الحساب من السيرفر عند حذف المستخدم')),
                ('default_library_ids', models.JSONField(blank=True, default=list, verbose_name='المكتبات الافتراضية الممنوحة')),
                ('default_policy', models.JSONField(blank=True, default=dict, verbose_name='سياسة الحساب الافتراضية (Policy)')),
                ('username_pattern', models.CharField(blank=True, default='LU-{lounge_id}', max_length=100, verbose_name='نمط توليد اسم المستخدم')),
                ('username_include_tenant', models.BooleanField(default=False, verbose_name='تضمين كود المستأجر في اسم المستخدم')),
                ('sync_interval_minutes', models.IntegerField(default=60, verbose_name='الفاصل الزمني للمزامنة (بالدقائق)')),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة شاملة')),
                ('last_user_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة لحسابات المستخدمين')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_servers', to='tenancy.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'خادم وسائط محلي (Media Server)',
                'verbose_name_plural': 'خوادم الوسائط المحلية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sync_type', models.CharField(choices=[('FULL', 'مزامنة شاملة (Full Sync)'), ('INCREMENTAL', 'مزامنة تزايدية (Incremental Sync)'), ('RECONCILIATION', 'مطابقة وإصلاح الفروقات (Reconciliation)'), ('LIBRARY', 'مزامنة مكتبة محددة (Single Library Sync)')], default='INCREMENTAL', max_length=32, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('RUNNING', 'قيد التنفيذ'), ('COMPLETED', 'اكتمل بنجاح'), ('FAILED', 'فشل'), ('PARTIAL', 'اكتمل جزئياً مع تحذيرات')], default='PENDING', max_length=32, verbose_name='حالة الوظيفة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('items_scanned', models.IntegerField(default=0, verbose_name='العناصر المفحوصة')),
                ('items_created', models.IntegerField(default=0, verbose_name='عناصر جديدة مضافة')),
                ('items_updated', models.IntegerField(default=0, verbose_name='عناصر تم تحديثها')),
                ('items_marked_unavailable', models.IntegerField(default=0, verbose_name='عناصر غير متوفرة')),
                ('items_deduplicated', models.IntegerField(default=0, verbose_name='عناصر تم دمجها منطقياً')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ إن وجدت')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل وإحصائيات إضافية')),
                ('media_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='media_servers.mediaserver', verbose_name='خادم الوسائط')),
            ],
            options={
                'verbose_name': 'مهمة مزامنة وسائط (Sync Job)',
                'verbose_name_plural': 'مهام مزامنة الوسائط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('external_user_id', models.CharField(db_index=True, max_length=128, verbose_name='معرّف المستخدم على السيرفر (External User ID)')),
                ('external_username', models.CharField(max_length=150, verbose_name='اسم المستخدم على السيرفر (External Username)')),
                ('external_password_encrypted', models.BinaryField(blank=True, null=True, verbose_name='كلمة المرور المشفرة (Fernet Encrypted)')),
                ('provisioning_mode', models.CharField(choices=[('MANUAL', 'يدوي (Manual Link)'), ('AUTO', 'تلقائي (Auto Created)'), ('DISABLED', 'معطل (Disabled)')], default='AUTO', max_length=20, verbose_name='نمط التزويد')),
                ('provisioning_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري التزويد'), ('COMPLETED', 'مكتمل بنجاح'), ('FAILED', 'فشل التزويد'), ('DISABLED', 'معطل مؤقتاً'), ('DELETED', 'محذوف من السيرفر')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة التزويد')),
                ('provisioning_error', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ الأخيرة')),
                ('provisioning_attempts', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تزويد ناجح')),
                ('sync_status', models.CharField(choices=[('IN_SYNC', 'متطابق (In Sync)'), ('OUT_OF_SYNC', 'غير متطابق (Out of Sync)'), ('UNKNOWN', 'غير معروف'), ('ERROR', 'خطأ في الفحص')], default='UNKNOWN', max_length=20, verbose_name='حالة التطابق مع السيرفر')),
                ('sync_details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل نتائج المزامنة')),
                ('media_server_policy', models.JSONField(blank=True, default=dict, verbose_name='سياسة الحساب على السيرفر (Policy)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التعطيل')),
                ('disabled_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب التعطيل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف')),
                ('deleted_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الحذف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات وصفية إضافية')),
                ('media_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='media_servers.mediaserver', verbose_name='خادم الوسائط')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_account_mappings', to='tenancy.tenant', verbose_name='المستأجر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_account_mappings', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم الاستراحة')),
            ],
            options={
                'verbose_name': 'ربط حساب خادم الوسائط (Media Account Mapping)',
                'verbose_name_plural': 'ربط حسابات خوادم الوسائط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaServerUserSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sync_type', models.CharField(choices=[('FULL', 'مزامنة شاملة (Full Sync)'), ('INCREMENTAL', 'مزامنة تزايدية (Incremental)'), ('RECONCILIATION', 'مطابقة وإصلاح الفروقات (Reconciliation)')], default='INCREMENTAL', max_length=30, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('RUNNING', 'قيد التنفيذ'), ('COMPLETED', 'اكتملت بنجاح'), ('FAILED', 'فشلت'), ('PARTIAL', 'اكتملت جزئياً مع تحذيرات')], default='PENDING', max_length=20, verbose_name='حالة المزامنة')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاكتمال')),
                ('users_checked', models.IntegerField(default=0, verbose_name='الحسابات المفحوصة')),
                ('users_created', models.IntegerField(default=0, verbose_name='حسابات منشأة')),
                ('users_updated', models.IntegerField(default=0, verbose_name='حسابات محدثة')),
                ('users_disabled', models.IntegerField(default=0, verbose_name='حسابات معطلة')),
                ('users_deleted', models.IntegerField(default=0, verbose_name='حسابات محذوفة')),
                ('mappings_fixed', models.IntegerField(default=0, verbose_name='ربط تم إصلاحه')),
                ('orphans_found', models.IntegerField(default=0, verbose_name='حسابات غير مرتبطة (Orphans)')),
                ('conflicts_found', models.IntegerField(default=0, verbose_name='تعارضات مكتشفة')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='آخر خطأ مسجل')),
                ('triggered_by', models.CharField(choices=[('SCHEDULED', 'مجدول دورياً'), ('MANUAL', 'يدوي من لوحة الإدارة'), ('EVENT', 'حدث نظام (Event Trigger)')], default='MANUAL', max_length=20, verbose_name='مصدر التشغيل')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='معرّف التتبع والترابط (Correlation ID)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إحصائية تفصيلية')),
                ('media_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_syncs', to='media_servers.mediaserver', verbose_name='خادم الوسائط')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_user_syncs', to='tenancy.tenant', verbose_name='المستأجر')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_media_syncs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الذي شغّل المزامنة')),
            ],
            options={
                'verbose_name': 'مزامنة حسابات خادم الوسائط (Media Server User Sync)',
                'verbose_name_plural': 'سجلات مزامنة حسابات خوادم الوسائط',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaServerOrphanUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('external_user_id', models.CharField(max_length=128, verbose_name='معرّف الحساب الخارجي')),
                ('external_username', models.CharField(max_length=150, verbose_name='اسم الحساب الخارجي')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاكتشاف')),
                ('status', models.CharField(choices=[('NEW', 'مكتشف حديثاً (New)'), ('IGNORED', 'تم التجاهل (Ignored)'), ('CLAIMED', 'تم ربطه بمستخدم (Claimed)'), ('DELETED', 'تم حذفه من السيرفر (Deleted)')], default='NEW', max_length=20, verbose_name='حالة الحساب المعزول')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الربط')),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإجراء')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات الحساب على السيرفر')),
                ('claimed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_media_orphans', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المربوط به')),
                ('media_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_users', to='media_servers.mediaserver', verbose_name='خادم الوسائط')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_media_orphans', to=settings.AUTH_USER_MODEL, verbose_name='المشرف الذي عيّن الإجراء')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphan_media_users', to='tenancy.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'حساب وسائط غير مربوط (Orphan Media User)',
                'verbose_name_plural': 'حسابات الوسائط غير المربوطة (Orphan Users)',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mediaaccountmapping',
            constraint=models.UniqueConstraint(fields=('user', 'media_server'), name='unique_user_media_server_mapping'),
        ),
        migrations.AddIndex(
            model_name='mediaaccountmapping',
            index=models.Index(fields=['media_server', 'provisioning_status'], name='idx_mam_srv_status'),
        ),
        migrations.AddIndex(
            model_name='mediaaccountmapping',
            index=models.Index(fields=['user', 'is_active'], name='idx_mam_user_active'),
        ),
        migrations.AddIndex(
            model_name='mediaserverusersync',
            index=models.Index(fields=['media_server', '-started_at'], name='idx_msus_srv_date'),
        ),
        migrations.AddConstraint(
            model_name='mediaserverorphanuser',
            constraint=models.UniqueConstraint(fields=('media_server', 'external_user_id'), name='unique_media_server_orphan_user'),
        ),
    ]
