# Generated by Django 5.1.15 on 2026-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_servers', '0002_phase14_media_server_advanced'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['media_server', 'status'], name='idx_syncjob_srv_status'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['sync_type', 'created_at'], name='idx_syncjob_type_date'),
        ),
    ]
