# Generated by Django 5.1.15 on 2026-09-13 16:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_default_onboarding_steps'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(db_index=True, max_length=64, verbose_name='تجزئة توكن الجلسة (SHA-256 Hash)')),
                ('refresh_token_hash', models.CharField(db_index=True, max_length=64, verbose_name='تجزئة توكن التجديد (SHA-256 Hash)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP للمتصل')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='وكيل المستخدم (User-Agent)')),
                ('device_fingerprint', models.CharField(blank=True, max_length=128, null=True, verbose_name='بصمة الجهاز (Fingerprint)')),
                ('mikrotik_session_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='معرّف جلسة MikroTik')),
                ('radius_session_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='معرّف جلسة RADIUS (Acct-Session-Id)')),
                ('source', models.CharField(choices=[('HOTSPOT', 'MikroTik Hotspot Portal'), ('RADIUS', 'RADIUS Direct'), ('SSO', 'Captive Portal SSO Redirect'), ('MANUAL', 'تسجيل دخول يدوي')], default='SSO', max_length=20, verbose_name='مصدر الجلسة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشطة (Active)'), ('EXPIRED', 'منتهية الصلاحية (Expired)'), ('REVOKED', 'ملغاة أمنياً (Revoked)')], db_index=True, default='ACTIVE', max_length=20, verbose_name='حالة الجلسة')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإصدار')),
                ('expires_at', models.DateTimeField(verbose_name='وقت انتهاء الصلاحية')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر نشاط')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('revoked_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الإلغاء')),
            ],
            options={
                'verbose_name': 'جلسة الاستراحة (Lounge Session)',
                'verbose_name_plural': 'جلسات الاستراحة',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='externalidentity',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'هوية خارجية (External Identity)', 'verbose_name_plural': 'الهويات الخارجية المربوطة'},
        ),
        migrations.RemoveConstraint(
            model_name='externalidentity',
            name='unique_identity_source',
        ),
        migrations.RenameIndex(
            model_name='onboardingstate',
            new_name='accounts_on_user_id_d9bfc1_idx',
            old_name='accounts_on_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingstate',
            new_name='accounts_on_status_926f69_idx',
            old_name='accounts_on_status_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingstate',
            new_name='accounts_on_tenant__6fdf9a_idx',
            old_name='accounts_on_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingsteptemplate',
            new_name='accounts_on_tenant__101c44_idx',
            old_name='accounts_ost_tenant_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingsteptemplate',
            new_name='accounts_on_step_ke_1c9777_idx',
            old_name='accounts_ost_step_key_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='accounts_us_user_id_1d0f83_idx',
            old_name='accounts_uc_user_type_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='accounts_us_consent_1ef38d_idx',
            old_name='accounts_uc_type_granted_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofilecompletion',
            new_name='accounts_us_user_id_756f85_idx',
            old_name='accounts_upc_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofilecompletion',
            new_name='accounts_us_is_opti_33fdf7_idx',
            old_name='accounts_upc_opt_idx',
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='أول ظهور'),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='موثّقة من الخادم الخارجي'),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر ظهور'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'تسجيل دخول ناجح'), ('FIRST_TIME_REGISTER', 'تسجيل دخول أول مرة (إنشاء مستخدم تلقائي)'), ('LOGIN_FAILED', 'فشل المصادقة'), ('TOKEN_REFRESH', 'تجديد توكن الجلسة'), ('SESSION_REVOKED', 'إلغاء جلسة'), ('SESSIONS_REVOKE_ALL', 'تسجيل خروج من جميع الأجهزة'), ('CARD_LINKED', 'ربط كارت/هوية جديدة بحساب موجود'), ('ROUTER_SYNC', 'مزامنة بوابة MikroTik'), ('RADIUS_AUTH', 'فحص مصادقة RADIUS'), ('ONBOARDING_STARTED', 'بدء مسار التهيئة والإعداد الأولي'), ('ONBOARDING_STEP_COMPLETED', 'إكمال خطوة في مسار التهيئة'), ('ONBOARDING_COMPLETED', 'اكتمال مسار التهيئة بنجاح'), ('CONSENT_GRANTED', 'منح موافقة قانونية'), ('CONSENT_REVOKED', 'إلغاء موافقة قانونية')], db_index=True, max_length=32, verbose_name='نوع الحدث'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='الهوية الرئيسية'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['external_id'], name='accounts_ex_externa_41e14f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['user'], name='accounts_ex_user_id_2609bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('identity_type', 'external_id'), name='unique_identity_type_external_id'),
        ),
        migrations.AddField(
            model_name='loungesession',
            name='external_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.externalidentity', verbose_name='الهوية الخارجية المستخدمة'),
        ),
        migrations.AddField(
            model_name='loungesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
        migrations.AddIndex(
            model_name='loungesession',
            index=models.Index(fields=['user', 'status'], name='accounts_lo_user_id_50de38_idx'),
        ),
        migrations.AddIndex(
            model_name='loungesession',
            index=models.Index(fields=['session_token_hash'], name='accounts_lo_session_8157e5_idx'),
        ),
        migrations.AddIndex(
            model_name='loungesession',
            index=models.Index(fields=['refresh_token_hash'], name='accounts_lo_refresh_a4b598_idx'),
        ),
    ]
