# Generated by Django 5.1.15 on 2026-09-13 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_seed_standard_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcepermissionoverride',
            options={'verbose_name': 'استثناء صلاحية على مستوى المورد', 'verbose_name_plural': 'استثناءات الصلاحيات على مستوى الموارد'},
        ),
        migrations.AlterModelOptions(
            name='usergroupassignment',
            options={'verbose_name': 'عضوية مستخدم في مجموعة', 'verbose_name_plural': 'عضويات المستخدمين في المجموعات'},
        ),
        migrations.AlterModelOptions(
            name='userpermissionoverride',
            options={'verbose_name': 'استثناء صلاحية مستخدم', 'verbose_name_plural': 'استثناءات صلاحيات المستخدمين'},
        ),
        migrations.RemoveField(
            model_name='usergroupassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='granted_by',
        ),
        migrations.AlterField(
            model_name='resourcepermissionoverride',
            name='is_granted',
            field=models.BooleanField(default=True, verbose_name='منح (True) / حظر صريح (False)'),
        ),
        migrations.AlterField(
            model_name='resourcepermissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_overrides', to='permissions.permission', verbose_name='الصلاحية المعنية'),
        ),
        migrations.AlterField(
            model_name='resourcepermissionoverride',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='resourcepermissionoverride',
            name='resource_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='معرّف المورد'),
        ),
        migrations.AlterField(
            model_name='resourcepermissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_overrides', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='is_granted',
            field=models.BooleanField(default=True, verbose_name='منح استثنائي (True) / حظر استثنائي (False)'),
        ),
    ]
