import uuid
import django.utils.timezone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='تجزئة التوكن (SHA-256)')),
                ('scope', models.CharField(choices=[('BROWSER', 'متصفح النظام (Browser Player)'), ('EXTERNAL', 'مشغل خارجي (External Player)'), ('CAST', 'بث عبر أجهزة كاست (Casting)')], default='BROWSER', max_length=20, verbose_name='نطاق التوكن')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف الجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP المصرح له')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تاريخ ووقت انتهاء الصلاحية')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الاستخدام')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_tokens', to='content.mediaitem', verbose_name='عنصر الوسائط')),
                ('media_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playback_tokens', to='content.mediasource', verbose_name='مصدر الوسائط الفيزيائي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توكن تشغيل آمن (Playback Token)',
                'verbose_name_plural': 'توكنات التشغيل الآمنة',
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(blank=True, default='جهاز غير معروف', max_length=150, verbose_name='اسم أو طراز الجهاز')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشطة (Active)'), ('PAUSED', 'موقوفة مؤقتاً (Paused)'), ('ENDED', 'منتهية (Ended)'), ('IDLE', 'خاملة (Idle)')], default='ACTIVE', max_length=20, verbose_name='حالة الجلسة')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت بدء المشاهدة')),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ آخر نبض (Heartbeat)')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إنهاء الجلسة')),
                ('current_position_seconds', models.IntegerField(default=0, verbose_name='الموضع الحالي بالثواني')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='المدة الكلية للعنصر بالثواني')),
                ('watched_seconds', models.IntegerField(default=0, verbose_name='مدة المشاهدة الفعلية بالثواني')),
                ('current_quality', models.CharField(default='AUTO', max_length=20, verbose_name='الجودة الحالية')),
                ('playback_method', models.CharField(choices=[('DIRECT_PLAY', 'تشغيل مباشر (Direct Play)'), ('DIRECT_STREAM', 'بث مباشر (Direct Stream)'), ('TRANSCODE', 'تحويل ترميز (Transcode)')], default='DIRECT_STREAM', max_length=30, verbose_name='طريقة البث')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات وصفية إضافية')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='content.mediaitem', verbose_name='عنصر الوسائط')),
                ('media_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='content.mediasource', verbose_name='المصدر الفيزيائي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة تشغيل (Playback Session)',
                'verbose_name_plural': 'جلسات التشغيل المراقبة',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف الجهاز الأخير')),
                ('position_seconds', models.IntegerField(default=0, verbose_name='موضع التوقف الحالي (بالثواني)')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='إجمالي مدة العنصر (بالثواني)')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الإكمال المئوية')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='هل اكتملت المشاهدة (>= 90%)')),
                ('last_watched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ ووقت آخر مشاهدة')),
                ('playback_method', models.CharField(choices=[('DIRECT_PLAY', 'تشغيل مباشر (Direct Play)'), ('DIRECT_STREAM', 'بث مباشر (Direct Stream)'), ('TRANSCODE', 'تحويل ترميز (Transcode)')], default='DIRECT_STREAM', max_length=30, verbose_name='طريقة التشغيل الأخيرة')),
                ('preferred_quality', models.CharField(blank=True, max_length=20, null=True, verbose_name='الجودة المفضلة أثناء المشاهدة')),
                ('preferred_audio', models.CharField(blank=True, max_length=50, null=True, verbose_name='المسار الصوتي المفضل')),
                ('preferred_subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملف الترجمة المفضل')),
                ('watch_time_seconds', models.IntegerField(default=0, verbose_name='إجمالي وقت المشاهدة الفعلي المقضي (دقيق)')),
                ('buffer_events_count', models.IntegerField(default=0, verbose_name='عدد مرات التخزين المؤقت (Buffer Events)')),
                ('quality_switches_count', models.IntegerField(default=0, verbose_name='عدد مرات تبديل الجودة')),
                ('last_playback_session_id', models.UUIDField(blank=True, null=True, verbose_name='معرف جلسة التشغيل الأخيرة')),
                ('sync_version', models.IntegerField(db_index=True, default=1, verbose_name='إصدار المزامنة عبر الأجهزة (Sync Version)')),
                ('updated_by_device', models.CharField(blank=True, max_length=150, null=True, verbose_name='الجهاز الأخير المحدّث للموضع')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to='content.mediaitem', verbose_name='عنصر الوسائط')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to='profiles.profile', verbose_name='البروفايل العائلي / الشخصي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مشاهدة واستئناف (Watch History)',
                'verbose_name_plural': 'سجلات المشاهدة والاستئناف',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePlayerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(db_index=True, max_length=100, verbose_name='معرف الجهاز')),
                ('default_quality', models.CharField(choices=[('AUTO', 'تلقائي (Auto)'), ('480p', '480p SD'), ('720p', '720p HD'), ('1080p', '1080p FHD'), ('4K', '4K Ultra HD')], default='AUTO', max_length=20, verbose_name='الجودة الافتراضية')),
                ('max_quality', models.CharField(choices=[('AUTO', 'تلقائي (Auto)'), ('480p', '480p SD'), ('720p', '720p HD'), ('1080p', '1080p FHD'), ('4K', '4K Ultra HD')], default='AUTO', max_length=20, verbose_name='الحد الأقصى للجودة')),
                ('auto_play_next', models.BooleanField(default=True, verbose_name='التشغيل التلقائي للحلقة التالية')),
                ('auto_skip_intro', models.BooleanField(default=False, verbose_name='تخطي المقدمة تلقائياً (Skip Intro)')),
                ('autoplay_preview', models.BooleanField(default=False, verbose_name='المعاينة التلقائية في الواجهة')),
                ('preferred_audio_language', models.CharField(blank=True, default='ar', max_length=50, null=True, verbose_name='لغة الصوت المفضلة (ar / en / original)')),
                ('preferred_subtitle_language', models.CharField(blank=True, default='ar', max_length=50, null=True, verbose_name='لغة الترجمة المفضلة')),
                ('subtitle_enabled_by_default', models.BooleanField(default=False, verbose_name='تفعيل الترجمة افتراضياً')),
                ('subtitle_size', models.CharField(choices=[('SMALL', 'صغير (Small)'), ('MEDIUM', 'متوسط (Medium)'), ('LARGE', 'كبير (Large)'), ('XLARGE', 'كبير جداً (X-Large)')], default='MEDIUM', max_length=20, verbose_name='حجم خط الترجمة')),
                ('subtitle_color', models.CharField(default='#FFFFFF', max_length=20, verbose_name='لون خط الترجمة')),
                ('subtitle_background', models.CharField(default='rgba(0,0,0,0.75)', max_length=50, verbose_name='خلفية شريط الترجمة')),
                ('subtitle_position', models.CharField(choices=[('BOTTOM', 'أسفل الشاشة (Bottom)'), ('TOP', 'أعلى الشاشة (Top)')], default='BOTTOM', max_length=20, verbose_name='موضع الترجمة على الشاشة')),
                ('playback_speed_default', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='سرعة التشغيل الافتراضية (1.0x, 1.25x...)')),
                ('volume_default', models.IntegerField(default=100, verbose_name='مستوى الصوت الافتراضي (0 - 100)')),
                ('skip_forward_seconds', models.IntegerField(default=10, verbose_name='مدة التخطي للأمام بالثواني')),
                ('skip_backward_seconds', models.IntegerField(default=10, verbose_name='مدة التخطي للخلف بالثواني')),
                ('keyboard_shortcuts_enabled', models.BooleanField(default=True, verbose_name='تفعيل اختصارات لوحة المفاتيح')),
                ('picture_in_picture_enabled', models.BooleanField(default=True, verbose_name='تفعيل نافذة صورة داخل صورة (PiP)')),
                ('external_player_preference', models.CharField(blank=True, max_length=50, null=True, verbose_name='المشغل الخارجي المفضل (vlc, infuse, kodi, mx_player, iina, nplayer)')),
                ('data_saver_mode', models.BooleanField(default=False, verbose_name='وضع توفير البيانات (Data Saver Mode - يمنع 4K ويحد البتات)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_player_preferences', to='tenancy.tenant', verbose_name='المستأجر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيل مشغل الجهاز (Device Player Preference)',
                'verbose_name_plural': 'تفضيلات مشغلات الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='PlaybackQualityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الجهاز')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ ووقت الحدث')),
                ('quality', models.CharField(max_length=20, verbose_name='الجودة المستهدفة')),
                ('bitrate_kbps', models.IntegerField(default=0, verbose_name='معدل البت بالكيلوبت (Bitrate kbps)')),
                ('buffer_health_seconds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='صحة الذاكرة المؤقتة (Buffer Health بالثواني)')),
                ('dropped_frames', models.IntegerField(default=0, verbose_name='عدد الإطارات الساقطة (Dropped Frames)')),
                ('playback_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='معدل سرعة التشغيل')),
                ('buffer_duration_seconds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='مدة التوقف المؤقت بالثواني')),
                ('event_type', models.CharField(choices=[('START', 'بدء التشغيل (Start)'), ('SWITCH', 'تبديل الجودة (Switch)'), ('BUFFER_START', 'بدء التخزين المؤقت (Buffer Start)'), ('BUFFER_END', 'انتهاء التخزين المؤقت (Buffer End)'), ('QUALITY_DOWN', 'خفض الجودة (Quality Down)'), ('QUALITY_UP', 'رفع الجودة (Quality Up)'), ('ERROR', 'خطأ في التشغيل (Playback Error)')], default='SWITCH', max_length=30, verbose_name='نوع حدث الجودة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات وصفية للحدث (السبب، تفاصيل الشبكة)')),
                ('playback_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='playback.playbacksession', verbose_name='جلسة التشغيل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_quality_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل جودة البث (Playback Quality Log)',
                'verbose_name_plural': 'سجلات جودة البث والتحليلات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchPartySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('WAITING', 'بانتظار البدء (Waiting)'), ('PLAYING', 'جاري المشاهدة (Playing)'), ('PAUSED', 'موقوف مؤقتاً (Paused)'), ('ENDED', 'منتهية (Ended)')], default='WAITING', max_length=20, verbose_name='حالة الجلسة الجماعية')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='الموعد المجدول')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الحفلة')),
                ('current_position_seconds', models.IntegerField(default=0, verbose_name='موضع المشاهدة الحالي للحفلة (بالثواني)')),
                ('playback_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='سرعة التشغيل المشتركة')),
                ('invite_code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='رمز الدعوة الفريد (Invite Code)')),
                ('is_public', models.BooleanField(default=False, verbose_name='متاحة للعامة في الاستراحة')),
                ('max_participants', models.IntegerField(default=10, verbose_name='الحد الأقصى للمشاركين')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات الجلسة الوصفية')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_watch_parties', to=settings.AUTH_USER_MODEL, verbose_name='المضيف الرئيسي (Host)')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_parties', to='content.mediaitem', verbose_name='عنصر الوسائط المشاهد')),
                ('media_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_parties', to='content.mediasource', verbose_name='مصدر الوسائط')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_parties', to='tenancy.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'جلسة مشاهدة جماعية (Watch Party Session)',
                'verbose_name_plural': 'جلسات المشاهدة الجماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchPartyParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف جهاز المشارك')),
                ('role', models.CharField(choices=[('HOST', 'المضيف الرئيسي (Host)'), ('VIEWER', 'مشاهد ومشارك (Viewer)')], default='VIEWER', max_length=20, verbose_name='دور المشارك (مضيف أم مشاهد)')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الانضمام')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت المغادرة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='متصل ونشط حالياً في الجلسة')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='playback.watchpartysession', verbose_name='جلسة المشاهدة الجماعية')),
                ('playback_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_participants', to='playback.playbacksession', verbose_name='جلسة التشغيل الفردية المرتبطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_party_participations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المشارك')),
            ],
            options={
                'verbose_name': 'مشارك في المشاهدة الجماعية (Party Participant)',
                'verbose_name_plural': 'مشاركو المشاهدة الجماعية',
            },
        ),
        migrations.CreateModel(
            name='CustomSubtitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('language', models.CharField(default='ar', max_length=20, verbose_name='رمز اللغة (ar, en...)')),
                ('label', models.CharField(max_length=150, verbose_name='تسمية الترجمة المعروضة (مثال: ترجمة عربية مخصصة)')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار تخزين الملف (VTT/SRT)')),
                ('file_format', models.CharField(choices=[('SRT', 'SubRip (.srt)'), ('VTT', 'WebVTT (.vtt)'), ('ASS', 'Advanced SubStation Alpha (.ass)')], default='VTT', max_length=10, verbose_name='صيغة الملف')),
                ('offset_seconds', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='إزاحة التزامن بالثواني (Offset Seconds)')),
                ('is_public', models.BooleanField(default=False, verbose_name='متاح لكافة مشاهدي الاستراحة')),
                ('approved', models.BooleanField(default=False, verbose_name='معتمد من إدارة الاستراحة')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_subtitles', to='content.mediaitem', verbose_name='عنصر الوسائط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_subtitles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الرافع')),
            ],
            options={
                'verbose_name': 'ملف ترجمة مخصص (Custom Subtitle)',
                'verbose_name_plural': 'ملفات الترجمة المخصصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(fields=('user', 'profile', 'media_item'), name='unique_user_profile_media_watch'),
        ),
        migrations.AddConstraint(
            model_name='deviceplayerpreference',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device_preference'),
        ),
        migrations.AddConstraint(
            model_name='watchpartyparticipant',
            constraint=models.UniqueConstraint(fields=('party', 'user'), name='unique_party_user_participant'),
        ),
    ]
