# Generated by Django 5.1.15 on 2026-09-13 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('playback', '0001_initial'),
        ('profiles', '0003_alter_profile_options_and_more'),
        ('tenancy', '0002_alter_site_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbacksession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'نشطة (Active)'), ('PAUSED', 'موقوفة مؤقتاً (Paused)'), ('ENDED', 'منتهية (Ended)'), ('IDLE', 'خاملة (Idle)')], db_index=True, default='ACTIVE', max_length=20, verbose_name='حالة الجلسة'),
        ),
        migrations.AlterField(
            model_name='watchpartysession',
            name='status',
            field=models.CharField(choices=[('WAITING', 'بانتظار البدء (Waiting)'), ('PLAYING', 'جاري المشاهدة (Playing)'), ('PAUSED', 'موقوف مؤقتاً (Paused)'), ('ENDED', 'منتهية (Ended)')], db_index=True, default='WAITING', max_length=20, verbose_name='حالة الجلسة الجماعية'),
        ),
        migrations.AddIndex(
            model_name='customsubtitle',
            index=models.Index(fields=['media_item', 'language'], name='playback_cu_media_i_f03adf_idx'),
        ),
        migrations.AddIndex(
            model_name='customsubtitle',
            index=models.Index(fields=['user', 'media_item'], name='playback_cu_user_id_9c3ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceplayerpreference',
            index=models.Index(fields=['user', 'device_id'], name='playback_de_user_id_cdb2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackqualitylog',
            index=models.Index(fields=['playback_session', 'timestamp'], name='playback_pl_playbac_ed99fe_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackqualitylog',
            index=models.Index(fields=['user', '-timestamp'], name='playback_pl_user_id_b088bc_idx'),
        ),
        migrations.AddIndex(
            model_name='playbacksession',
            index=models.Index(fields=['user', 'status', '-last_heartbeat_at'], name='playback_pl_user_id_2dddb7_idx'),
        ),
        migrations.AddIndex(
            model_name='playbacksession',
            index=models.Index(fields=['device_id', 'status'], name='playback_pl_device__083830_idx'),
        ),
        migrations.AddIndex(
            model_name='playbacktoken',
            index=models.Index(fields=['user', 'expires_at'], name='playback_pl_user_id_f75355_idx'),
        ),
        migrations.AddIndex(
            model_name='playbacktoken',
            index=models.Index(fields=['token_hash'], name='playback_pl_token_h_aacb92_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', 'profile', '-last_watched_at'], name='playback_wa_user_id_7b1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['sync_version'], name='playback_wa_sync_ve_082405_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['media_item', 'is_completed'], name='playback_wa_media_i_a3450e_idx'),
        ),
        migrations.AddIndex(
            model_name='watchpartyparticipant',
            index=models.Index(fields=['party', 'is_active'], name='playback_wa_party_i_b46335_idx'),
        ),
    ]
